version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: prisma_test
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma

    #network_mode: "host"
 
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data


      